---
- name: Perform full system upgrade
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  become: true
  pacman:
    name: "{{ packages.essential }}"
    state: present
