---
- name: Init /etc/systemd/timesyncd.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf
    src: timesyncd.conf

- name: Enable systemd-timesyncd
  become: yes
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
