---

- name: ensure group {{ user.group }} exists
  group:
    name: "{{ user.group }}"
    state: present
  when: user.name is defined and user.group is defined


- name: ensure the user {{ user.name }} exists
  user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
        - "{{ user.group }}"
        - wheel
        - lock
        - uucp
    append: yes
    system: no
    createhome: yes
    home: /home/{{ user.name }}
  when: user.name is defined


- name: Give sudo rights to users in wheel group
  copy:
    dest: /etc/sudoers
    src: sudoers
    mode: 0440