---

- name: Install flatpak
  become: yes
  community.general.pacman: 
    pkg: flatpak

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user