---
- name: Install docker
  become: true
  ansible.builtin.package:
    pkg:
      - docker
      - docker-compose

- name: "Add current user to 'docker' group: ({{ username }})"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
    append: true

- name: Start/Enable docker systemd service
  become: true
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
