---

- name: Install nordic gtk3 theme
  aur:
    name: nordic-theme-git
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Install papirus icon theme
  pacman:
    name: papirus-icon-theme
    state: present

- name: Create gtk3 settings directory
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user.name }}"
    mode: 0750

- name: Copy gtk3 settings
  copy:
    dest: "/home/{{ user.name }}/.config/gtk-3.0/settings.ini"
    src: 'gtk-3.0/settings.ini'