---
- name: Install nordic gtk3 theme
  kewlfft.aur.aur:
    name: nordic-theme
  become: true
  become_user: aur_builder

- name: Install papirus icon theme
  become: true
  ansible.builtin.package:
    pkg: papirus-icon-theme
