---
system:
  locale: de_DE

timezone: Europe/Stockholm

user:
  name: macgyves
  group: users
  shell: /bin/zsh

packages:
  essential:
    - base
    - base-devel
    - linux
    - linux-firmware
    - lvm2
    - ansible
    - neovim
    - git
    - zsh
  more:
    - alacritty
    - curl
    - openssh
    - rsync
    - man-db
    - unzip
    - zip
    - keepassxc
    - qt5-wayland # needed for keepassxc
    - nnn
    - python-pip
    - python-pexpect # required by ansible.builtin.expect
    - python-psutil # required by community.general.dconf
    - vlc
    - firefox
    - chromium
    - pipewire
    - pipewire-pulse
    - youtube-dl
    - task # taskwarrior
    - fwupd # firmware-update daemon
    - transmission-gtk

partitions:
  luks:
    dev: /dev/nvme0n1p2