---
system:
  locale: de_DE
  processor: intel

vconsole:
  keymap: uk

hostname: "Thinx"

timezone: Europe/Stockholm

partitions:
  esp:
    label: "ESP"
    dev: "/dev/disk/by-partlabel/ESP"
  luks:
    label: "CRYPTROOT"
    dev: "/dev/disk/by-partlabel/CRYPTROOT"

user:
  name: macgyves
  shell: /bin/zsh

packages:
  essential:
    - base
    - base-devel
    - linux
    - linux-firmware
    - ansible
    - neovim
    - git
    - zsh
    - curl
    - openssh
    - rsync
    - man-db
    - unzip
    - zip
    - keepassxc
    - qt5-wayland # needed for keepassxc
    - fwupd # firmware-update daemon
    - transmission-gtk
    - python-pip
    - python-pexpect # required by ansible.builtin.expect
    - python-psutil # required by community.general.dconf
    - python-passlib # required by ansible to hash variables
    - vlc
    - firefox
    - chromium
    - sof-firmware
    - pipewire
    - pipewire-pulse
    - youtube-dl
    - task # taskwarrior
  headless:
    - alacritty
    - nnn
