hostname: 'ThinkR'

system:
    processor: intel

timezone: Europe/Stockholm

partitions:
    boot:
        label: 'BOOT'
        dev: "/dev/disk/by-partlabel/BOOT"
    luks:
        label: 'LUKS'
        dev: '/dev/disk/by-partlabel/LUKS'
        mapper_name: 'cryptlvm'

lvm:
    vg_main: 'vg.main'
    lv_root:
        name: 'root'
        label: 'ROOT'
        dev: '/dev/vg.main/root'
    lv_swap:
        name: 'swap'
        label: 'SWAP'
        dev: '/dev/vg.main/swap'

user:
    name: macgyves
    group: users
    shell: /bin/zsh


base_packages:
    - base-devel
    - curl
    - git
    - openssh
    - rsync
    - zsh

# tmp
more_packages:
    - kate
    - dolphin
    - konsole
    - okular
    - gwenview
    - spectacle
    - ark
    - unzip
    - zip
    - openssh
    - baobab
    - gramps
    - firefox
    - chromium
    - vlc
    - libreoffice-fresh
    - calibre
    - keepassxc
    - digikam
    - freemind
    - gimp
    - ttf-hack
    - docker
    - docker-compose
    # 3G modem
    #- modem-manager-gui
    # smartcard
    - ccid
    - opensc
    - xloadimage
    # firewall
    - nextcloud-client
