---
- name: Ensure directory /etc/systemd/system/getty@tty1.service.d exists
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Create drop-in-snippet for getty@tty1.service
  become: yes
  ansible.builtin.template:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    src: getty@tty1.service.override.conf.j2
