---
- name: Install sudo
  ansible.builtin.package:
    pkg: sudo

- name: "Ensure current user exists ({{ username }})"
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ user.shell }}"
    createhome: true
    home: "/home/{{ username }}"

- name: "Add current user to sudoers ({{ username }})"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/00_{{ username }}"
    state: present
    line: "{{ username }} ALL=(ALL) ALL"
    validate: /usr/sbin/visudo -cf %s
    create: true
    mode: "0750"

- name: Customize sudo
  become: true
  ansible.builtin.copy:
    dest: /etc/sudoers.d/env_keep
    src: sudoers.d/env_keep
    mode: "0440"

- name: "Restrict root login"
  become: true
  ansible.builtin.user:
    name: "root"
    password: "!"
