---
- name: "Ensure the user {{ user.name }} exists"
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - lock
      - uucp
    append: yes
    system: no
    createhome: yes
    home: "/home/{{ user.name }}"
  when: user.name is defined

- name: Setup sudo
  become: yes
  ansible.builtin.copy:
    dest: /etc/sudoers.d/env_keep
    src: sudoers.d/env_keep
    mode: 0440

#- import_tasks: auto_login_user.yml
