---
- name: Install sudo
  community.general.pacman:
    pkg: sudo

- name: "Ensure user {{ username }} exists"
  become: yes
  ansible.builtin.user:
    name: "{{ username }}"
    shell: "{{ user.shell }}"
    createhome: yes
    home: "/home/{{ username }}"

- name: "Add user {{ username }} to sudoers"
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/00_{{ username }}"
    state: present
    line: "{{ username }} ALL=(ALL) ALL"
    validate: /usr/sbin/visudo -cf %s
    create: yes

- name: Customize sudo
  become: yes
  ansible.builtin.copy:
    dest: /etc/sudoers.d/env_keep
    src: sudoers.d/env_keep
    mode: 0440

- name: "Restrict root login"
  become: yes
  ansible.builtin.user:
    name: "root"
    password: "!"
