---
- name: "Ensure group {{ user.group }} exists"
  become: yes
  group:
    name: "{{ user.group }}"
    state: present

- name: "Ensure the user {{ user.name }} exists"
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - wheel
      - lock
      - uucp
    append: yes
    system: no
    createhome: yes
    home: "/home/{{ user.name }}"
    password: "{{ user_password }}"
  when: user.name is defined
  no_log: true

- name: Init /etc/sudoers
  become: yes
  ansible.builtin.copy:
    dest: /etc/sudoers
    src: sudoers
    mode: 0440

- import_tasks: auto_login_user.yml
- import_tasks: create_aur_builder_user.yml
