---
- name: Install sudo
  community.general.pacman:
    pkg: sudo

- name: "Create user {{ user.name }}"
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - lock
      - uucp
    append: yes
    system: no
    createhome: yes
    home: "/home/{{ user.name }}"

- name: "Grant user {{ user.name }} sudo permissions"
  become: yes
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/00_{{ user.name }}"
    state: present
    line: "{{ user.name }} ALL=(ALL) ALL"
    validate: /usr/sbin/visudo -cf %s
    create: yes

- name: Setup sudo
  become: yes
  ansible.builtin.copy:
    dest: /etc/sudoers.d/env_keep
    src: sudoers.d/env_keep
    mode: 0440
