---
- name: "Ensure group {{ user.group }} exists"
  become: yes
  group:
    name: "{{ user.group }}"
    state: present

- name: "Ensure the user {{ user.name }} exists"
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: "{{ user.shell }}"
    groups:
      - "{{ user.group }}"
      - wheel
      - lock
      - uucp
    append: yes
    system: no
    createhome: yes
    home: "/home/{{ user.name }}"
    password: "{{ user_password }}"
  when: user.name is defined
  no_log: true

- name: Init /etc/sudoers
  become: yes
  ansible.builtin.copy:
    dest: /etc/sudoers
    src: sudoers
    mode: 0440

- name: Ensure directory /etc/systemd/system/getty@tty1.service.d exists
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory

- name: Create drop-in-snippet for getty@tty1.service
  become: yes
  ansible.builtin.template:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    src: getty@tty1.service.override.conf.j2

- import_tasks: create_aur_builder_user.yml
