repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        name: Prettier
        description: Format code with prettier
  - repo: https://github.com/ansible/ansible-lint
    rev: v6.17.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        name: Ansible Lint
        description: Run linting with config from .ansible-lint file
        args: [-c, .config/ansible-lint.yml]
