- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      pacman: name={{item}}
      with_items:
        - firefox
        - libreoffice-fresh
        - calibre
        - keepassxc
        - digikam
        - virtualbox
        - nextcloud-client
        - zsh
        - openssh

    - name: Configure timezone
      file:
        src: /usr/share/zoneinfo/Europe/Stockholm
        dest: /etc/localtime
        state: link

    - name: Sync time with hardware clock
      command: hwclock --systohc --utc