- hosts: localhost
  become: true
  tasks:
    - name: Install packages
      pacman: name={{item}}
      with_items:
        - firefox
        - libreoffice-fresh
        - calibre
        - keepassxc
        - digikam
        - virtualbox
        - nextcloud-client
        - zsh
        - openssh