---
- name: Install gnome-specific packages
  become: true
  community.general.pacman:
    pkg:
      - evince
      - gedit

- name: Uninstall unnecessary gnome apps
  become: true
  community.general.pacman:
    pkg:
      - epiphany
    state: absent