---
- name: Install gnome desktop
  become: true
  ansible.builtin.package:
    pkg:
      - gnome
      - evince # a.k.a. "Document Viewer"
      - nautilus # a.k.a. "Files"
      - seahorse # a.k.a. "Passwords and Keys"
      #      - gnome-shell-extension-gtile
      - gnome-shell-extension-appindicator
      - dconf-editor

- name: Uninstall unnecessary gnome apps
  become: true
  ansible.builtin.package:
    pkg:
      - epiphany
      - totem
      - gnome-photos
      - gnome-software
      - gnome-terminal
    state: absent

- name: Install gnome-shell-pomodoro from AUR
  kewlfft.aur.aur:
    name:
      - gnome-shell-pomodoro
  become: true
  become_user: aur_builder

- name: Enable gdm.service
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    enabled: true

- name: "Write dconf values for /org/gnome/"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ org_gnome_dconf | dict2items }}"

  # - name: "Setup Gnome Material Shell"
  #  ansible.builtin.include_tasks: material_shell.yml
