---
- name: Install gnome desktop
  become: true
  community.general.pacman:
    pkg:
      - gnome
      - evince # a.k.a. "Document Viewer"
      - nautilus # a.k.a. "Files"
      - seahorse # a.k.a. "Passwords and Keys"
      - gnome-shell-extension-gtile
      - gnome-shell-extension-appindicator

- name: Uninstall unnecessary gnome apps
  become: true
  community.general.pacman:
    pkg:
      - epiphany
      - totem
      - gnome-photos
      - gnome-software
      - gnome-terminal
    state: absent

- name: Install gnome-shell-pomodoro from AUR
  kewlfft.aur.aur:
    name:
      - gnome-shell-pomodoro
  become: yes
  become_user: aur_builder

- name: Enable gdm.service
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    enabled: yes

- name: "Write dconf values for /org/gnome/"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ org_gnome_dconf | dict2items }}"

- include_tasks: material_shell.yml
