---
- name: Install gnome desktop
  become: true
  community.general.pacman:
    pkg:
      - gnome
      - evince # a.k.a. "Document Viewer"
      - nautilus # a.k.a. "Files"
      - seahorse # a.k.a. "Passwords and Keys"
      - gedit
      - gnome-shell-extension-gtile
      - gnome-shell-extension-appindicator

- name: Uninstall unnecessary gnome apps
  become: true
  community.general.pacman:
    pkg:
      - epiphany
    state: absent

- name: Start/Enable gdm.service
  become: true
  ansible.builtin.systemd:
    name: gdm.service
    state: started
    enabled: yes

- name: "Write dconf values for /org/gnome/"
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop: "{{ org_gnome_dconf | dict2items }}"