---
- name: Install antibody (zsh plugin manager)
  kewlfft.aur.aur:
    name: antibody
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

## Needed for syntax highlighting in less
- name: Install GNU syntax-highlighting
  become: yes
  community.general.pacman:
    package: source-highlight
