---

- name: "Ensure /home/{{user.name}}/.oh-my-zsh does not exist"
  file:
    path: "/home/{{user.name}}/.oh-my-zsh"
    state: absent


- name: Install oh-my-zsh
  aur:
    name: oh-my-zsh-git
#        - mytourbook_bin
      #          - tor-browser
#        -
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder
  tags: 'aur-packages'

- name: "Use oh-my-zsh in {{user.name}}'s zsh"
  command: /usr/share/oh-my-zsh/tools/install.sh
  become: yes
  become_user: "{{ user.name }}"

- name: Copy .zshrc
  copy:
    dest: /home/{{ user.name }}/.zshrc
    src: .zshrc
#      add "asdf" to oh-my-zsh plugins


- name: Install fish-like syntax highlighting and autosuggestions
  pacman:
    name:
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present
