---
- name: Install shell tools/customizations
  kewlfft.aur.aur:
    name:
      - zsh-antidote
      - git-extras
  become: yes
  become_user: aur_builder

## Needed for syntax highlighting in less
- name: Install GNU syntax-highlighting
  become: yes
  community.general.pacman:
    package: source-highlight
