---
- name: Install shell tools/customizations
  kewlfft.aur.aur:
    name:
      - zsh-antidote
      - git-extras
  become: true
  become_user: aur_builder

## Needed for syntax highlighting in less
- name: Install GNU syntax-highlighting
  become: true
  ansible.builtin.package:
    package: source-highlight
