---
- name: Install util-linux package
  become: yes
  community.general.pacman:
    pkg: util-linux
    state: present

- name: Schedule weekly SSD TRIM
  become: yes
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: yes
