---
- name: Install util-linux package
  become: true
  ansible.builtin.package:
    pkg: util-linux
    state: present

- name: Schedule weekly SSD TRIM
  become: true
  ansible.builtin.systemd:
    name: fstrim.timer
    enabled: true
