---
- name: Install messengers/office/nextcloud
  become: true
  community.general.pacman:
    pkg:
      - signal-desktop
      - telegram-desktop
      - thunderbird
      - libreoffice-fresh
      - nextcloud-client
