---
- name: Install office packages
  become: true
  community.general.pacman:
    name:
      - vdirsyncer
      - khard
    state: present

- import_tasks: nextcloud.yml
- import_tasks: vdirsyncer.yml
