---
- name: Install terminal mail/office packages
  become: true
  community.general.pacman:
    pkg:
      - vdirsyncer
      - khard
      - neomutt
      - notmuch
      # - urlview // <- from AUR!
      - isync
      - msmtp
      - pass
      - lynx

- name: Install messengers
  become: true
  community.general.pacman:
    pkg:
      - signal-desktop
      - telegram-desktop

- import_tasks: nextcloud.yml
- import_tasks: vdirsyncer.yml
