---
- name: Install messengers
  become: true
  community.general.pacman:
    pkg:
      - signal-desktop
      - telegram-desktop
      - thunderbird
      - libreoffice-fresh

- name: Install nextcloud desktop sync client
  become: yes
  community.general.pacman:
    pkg:
      - nextcloud-client
