---
#- name: Install terminal mail/office packages
#  become: true
#  community.general.pacman:
#    pkg:
#      - vdirsyncer
#      - khard
#      - neomutt
#      - notmuch
#      # - urlview // <- from AUR!
#      - isync
#      - msmtp
#      - pass
#      - lynx

#- import_tasks: vdirsyncer.yml

- name: Install messengers
  become: true
  community.general.pacman:
    pkg:
      - signal-desktop
      - telegram-desktop
      - thunderbird
- import_tasks: nextcloud.yml
