---
- name: Install messengers/office/nextcloud
  become: true
  community.general.pacman:
    pkg:
      - signal-desktop
      - telegram-desktop
      - thunderbird
      - libreoffice-fresh
      - nextcloud-client

- name: Install slack as flatpak
  community.general.flatpak:
    name: com.slack.Slack
    method: user

- name: Install gnome-shell-pomodoro from AUR
  kewlfft.aur.aur:
    name:
      - gnome-shell-pomodoro
  become: yes
  become_user: aur_builder
