---

- name: Install office packages
  become: true
  become_user: macgyves
  pacman: 
    name: 
      - vdirsyncer
      - khard
    state: present
    
- import_tasks: nextcloud.yml
- import_tasks: vdirsyncer.yml