---
- name: Install messengers/office/nextcloud
  become: true
  ansible.builtin.package:
    pkg:
      - signal-desktop
      - telegram-desktop
      - thunderbird
      - libreoffice-fresh
      - nextcloud-client

- name: Install slack as flatpak
  community.general.flatpak:
    name: com.slack.Slack
    method: user
