---
- name: Install office packages
  become: true
  community.general.pacman:
    pkg:
      - vdirsyncer
      - khard
      - neomutt
      - notmuch
      # - urlview // <- from AUR!
      - isync
      - msmtp
      - pass
      - lynx
    state: present

- import_tasks: nextcloud.yml
- import_tasks: vdirsyncer.yml
