---
- name: Ensure contacts folders exist
  file: 
    path: "~/contacts/contacts"
    state: directory

- name: Run vdirsyncer discover
  command: vdirsyncer discover

- name: Run initial vdirsyncer sync
  command: vdirsyncer sync

- name: Ensure systemd user directory (~/.config/systemd/user) exists
  file: 
    path: "/home/{{ user.name }}/.config/systemd/user"
    state: directory

- name: Ensure vdirsyncer.service systemd unit is installed
  copy: 
    dest: "/home/{{ user.name }}/.config/systemd/user"
    src: .config/systemd/user/vdirsyncer.service

- name: Ensure vdirsyncer.timer systemd unit is installed
  copy: 
    dest: "/home/{{ user.name }}/.config/systemd/user"
    src: .config/systemd/user/vdirsyncer.timer

- name: Enable vdirsyncer timer
  systemd:
    name: vdirsyncer.timer
    scope: user
    state: started
    enabled: yes
    daemon_reload: yes

