---
- name: Push mkinitcpio configuration and regenerate initramfs
  become: yes
  ansible.builtin.template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
  notify:
    - regenerate initramfs
