---
- name: Update mkinitcpio.conf and trigger regenerate initramfs
  become: true
  ansible.builtin.template:
    src: mkinitcpio.conf.j2
    dest: /etc/mkinitcpio.conf
    mode: "0644"
  notify:
    - "Regenerate initramfs"
