---

- name: Install sddm
  pacman:
    name:
      - sddm
#      - sddm-kcm
    state: present

- name: Enable sddm
  systemd:
    name: sddm.service
#    state: started
    enabled: yes

- name: Assert sddm.conf.d config directory exists
  file:
    path: /etc/sddm.conf.d
    state: directory
    mode: 0755

- name: Activate autologin
  template:
    dest: /etc/sddm.conf.d/autologin.conf
    src: autologin.conf.j2
    mode: 644

- name: sddm theme
  copy:
    dest: /etc/sddm.conf.d/theme.conf
    src: theme.conf
    mode: 644

- name: Install plasma
  pacman:
    name: plasma-desktop
    state: present

