---
- name: Perform full system upgrade
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  become: true
  community.general.pacman:
    pkg: "{{ packages.essential }}"

- name: Install more packages
  become: true
  community.general.pacman:
    pkg: "{{ packages.more }}"
