---
- name: Perform full system upgrade
  become: true
  community.general.pacman:
    update_cache: yes
    upgrade: yes

- name: Install base packages
  become: true
  community.general.pacman:
    pkg: "{{ packages.essential }}"

- name: Install host-specific packages
  become: true
  community.general.pacman:
    pkg: "{{ host_specific.packages }}"
  when: host_specific.packages | length > 0
