---
- name: Register if private ssh resident key exist
  ansible.builtin.stat:
    path: "{{ private_ssh_key.path }}"
  register: private_ssh_key_stat

- name: Register if public ssh resident key exist
  ansible.builtin.stat:
    path: "{{ public_ssh_key.path }}"
  register: public_ssh_key_stat

- name: Setup ssh to use resident keys on YubiKey
  block:
    - name: Fetch resident key from YubiKey
      # The command below places the keys in the "current" folder, i.e. the ansible "playbook_dir"
      ansible.builtin.expect:
        command: "ssh-keygen -K"
        responses:
          Enter PIN for authenticator: "{{ yubikey_pin }}"
          Overwrite: "y"
          Enter passphrase: ""
          Enter same passphrase again: ""

    - name: Move fetched resident key to ~/.ssh
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/id_ed25519_sk_rk"
        dest: "{{ private_ssh_key.path }}"
        mode: "0600"

    - name: Move fetched resident public key to ~/.ssh
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/id_ed25519_sk_rk.pub"
        dest: "{{ public_ssh_key.path }}"

    - name: Cleanup fetched resident keys from temp dir
      ansible.builtin.file:
        state: absent
        path: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/id_ed25519_sk_rk.pub"
        - "{{ playbook_dir }}/id_ed25519_sk_rk"
  when: not private_ssh_key_stat.stat.exists or not public_ssh_key_stat.stat.exists
