---
- name: "Read device information"
  community.general.parted:
    device: "{{ install_disk }}"
    unit: MiB
  register: install_disk_info

- name: "Remove all partitions from {{ install_disk }}"
  community.general.parted:
    device: "{{ install_disk }}"
    number: "{{ item.num }}"
    state: absent
  loop: "{{ install_disk_info.partitions }}"
