---
- name: "Remove LUKS container on device {{ partitions.luks.dev }}"
  community.crypto.luks_device:
    device: "{{ partitions.luks.dev }}"
    state: "absent"

- name: "Create and open LUKS container on device {{ partitions.luks.dev }} with label {{ partitions.luks.label }} and name {{ partitions.luks.mapper_name }}"
  community.crypto.luks_device:
    device: "{{ partitions.luks.dev }}"
    label: "{{ partitions.luks.label }}"
    name: "{{ partitions.luks.mapper_name }}"
    state: "opened"
    passphrase: "{{ luks_password }}"
    type: luks2
