---
- name: Create main LVM volume group
  lvg:
    vg: "{{ lvm.vg_main }}"
    pvs: "/dev/mapper/{{ partitions.luks.mapper_name }}"

- name: Create logical volume for swap
  lvol:
    vg: "{{ lvm.vg_main }}"
    lv: "{{ lvm.lv_swap.name }}"
    size: "{{ ansible_memtotal_mb | string }}"

- name: Create logical volume for root
  lvol:
    vg: "{{ lvm.vg_main }}"
    lv: "{{ lvm.lv_root.name }}"
    size: 100%FREE
