---
- name: Create EFI System Partition
  parted:
    device: "{{ install_disk }}"
    name: "{{ partitions.esp }}"
    number: 1
    label: gpt
    flags: [ esp, boot ]
    state: present
    part_end: 551MiB

- name: Create LUKS2 encrypted partition
  parted:
    device: "{{ install_disk }}"
    name: "{{ partitions.encrypted }}"
    number: 2
    label: gpt
    state: present
    part_start: 551MiB