---
- name: Format ESP as FAT32
  filesystem:
    fstype: vfat
    dev: "/dev/disk/by-partlabel/{{ partitions.esp }}"
    opts: -F32 -n EFI

- name: Format vg.main-swap
  command: mkswap /dev/vg.main/swap

- name: Format vg.main-root
  filesystem:
    fstype: ext4
    dev : /dev/vg.main/root