---
- name: Format ESP as FAT32
  filesystem:
    fstype: vfat
    dev: "{{ partitions.boot.dev }}"
    opts: "-F32 -n {{ partitions.boot.label }}"

- name: Set swap volume as swap area
  filesystem:
    fstype: swap
    dev: "{{ lvm.lv_swap.dev }}"
    opts: "-L {{ lvm.lv_swap.label }}"

- name: Format root volume
  filesystem:
    fstype: ext4
    dev: "{{ lvm.lv_root.dev }}"
    opts: "-L {{ lvm.lv_root.label }}"
