---
- name: Mount root volume
  mount:
    path: /mnt
    src: /dev/vg.main/root
    fstype: ext4
    state: mounted

- name: Mount ESP
  mount:
    name: /mnt/boot
    src: "/dev/disk/by-partlabel/{{ partitions.esp }}"
    fstype: vfat
    state: mounted

- name: Activate swapping on vg.main-swap
  command: swapon /dev/vg.main/swap