---
# pacstrap fails if intel-ucode exists on boot partition.
- name: Delete intel-ucode.img
  file:
    path: "{{ arch_root }}/boot/intel-ucode.img"
    state: absent

- name: Install essential packages
  command: "pacstrap {{ arch_root }} {{ packages.essential | join(' ')}}"
  retries: 3
  delay: 2
  tags: "pacstrap"
