---
- name: Create EFI System Partition
  parted:
    device: "{{ install_disk }}"
    name: "{{ partitions.boot.label }}"
    number: 1
    label: gpt
    flags: [esp]
    state: present
    part_end: 551MiB

- name: Create LUKS partition
  parted:
    device: "{{ install_disk }}"
    name: "{{ partitions.luks.label }}"
    number: 2
    label: gpt
    state: present
    part_start: 551MiB
