---
- name: "Init /etc/locale.gen and generate locales"
  become: true
  community.general.locale_gen:
    name: "{{ system.locale }}.UTF-8"

- name: Init /etc/locale.conf
  become: true
  ansible.builtin.template:
    dest: /etc/locale.conf
    src: locale.conf.j2
    mode: "0644"

- name: Init /etc/vconsole.conf
  become: true
  ansible.builtin.template:
    dest: /etc/vconsole.conf
    src: vconsole.conf.j2
    mode: "0644"
