org_gnome_dconf:
  "/org/gnome/Console/theme": "'auto'"
  "/org/gnome/Weather/locations": "[<(uint32 2, <('Göteborg', 'ESGP', true, [(1.0085094136262927, 0.2074032869608953)], [(1.007345872427158, 0.20885773963975227)])>)>]"
  "/org/gnome/desktop/background/color-shading-type": "'solid'"
  "/org/gnome/desktop/background/picture-options": "'zoom'"
  "/org/gnome/desktop/background/picture-uri": "'file:///usr/share/backgrounds/gnome/dune-l.svg'"
  "/org/gnome/desktop/background/picture-uri-dark": "'file:///usr/share/backgrounds/gnome/dune-d.svg'"
  "/org/gnome/desktop/background/primary-color": "'#f7a957'"
  "/org/gnome/desktop/background/secondary-color": "'#000000'"
  "/org/gnome/desktop/input-sources/sources": "[('xkb', 'gb'), ('xkb', 'de'), ('xkb', 'se')]"
  "/org/gnome/desktop/input-sources/xkb-options": "['terminate:ctrl_alt_bksp', 'compose:rctrl', 'lv3:ralt_switch', 'caps:escape']"
  "/org/gnome/desktop/interface/clock-show-seconds": "false"
  "/org/gnome/desktop/interface/clock-show-weekday": "false"
  "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
  "/org/gnome/desktop/interface/font-antialiasing": "'grayscale'"
  "/org/gnome/desktop/interface/font-hinting": "'slight'"
  "/org/gnome/desktop/interface/show-battery-percentage": "false"
  "/org/gnome/desktop/interface/text-scaling-factor": "1.25"
  "/org/gnome/desktop/interface/toolkit-accessibility": "false"
  "/org/gnome/desktop/peripherals/keyboard/numlock-state": "true"
  "/org/gnome/desktop/search-providers/sort-order": "['org.gnome.Contacts.desktop', 'org.gnome.Documents.desktop', 'org.gnome.Nautilus.desktop']"
  "/org/gnome/desktop/wm/keybindings/close": "['<Shift><Super>q']"
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-1": "['<Shift><Super>1']"
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-2": "['<Shift><Super>2']"
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-3": "['<Shift><Super>3']"
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-4": "['<Shift><Super>4']"
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1": "['<Super>1']"
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2": "['<Super>2']"
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3": "['<Super>3']"
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4": "['<Super>4']"
  "/org/gnome/desktop/wm/keybindings/toggle-fullscreen": "['<Super>f']"
  "/org/gnome/desktop/wm/preferences/workspace-names": "['Info', 'Kommunikation', 'Arbeit']"
  "/org/gnome/settings-daemon/plugins/media-keys/calculator": "['Calculator']"
  "/org/gnome/settings-daemon/plugins/media-keys/control-center": "['<Shift><Super>p']"
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings": "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']"
  "/org/gnome/settings-daemon/plugins/media-keys/email": "['Mail']"
  "/org/gnome/settings-daemon/plugins/media-keys/home": "['HomePage']"
  "/org/gnome/settings-daemon/plugins/media-keys/logout": "['<Control><Alt><Super>e']"
  "/org/gnome/settings-daemon/plugins/media-keys/screensaver": "['<Control><Alt><Super>l']"
  "/org/gnome/settings-daemon/plugins/media-keys/search": "['<Super>d']"
  "/org/gnome/settings-daemon/plugins/media-keys/www": "['<Shift><Super>f']"
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding": "'<Super>Return'"
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command": "'kgx'"
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name": "'Konsole öffnen'"
  "/org/gnome/shell/disable-user-extensions": "false"
  "/org/gnome/shell/disabled-extensions": "['apps-menu@gnome-shell-extensions.gcampax.github.com', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'window-list@gnome-shell-extensions.gcampax.github.com', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com']"
  "/org/gnome/shell/enabled-extensions": "['workspace-indicator@gnome-shell-extensions.gcampax.github.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'gTile@vibou', 'appindicatorsupport@rgcjonas.gmail.com']"
  "/org/gnome/shell/favorite-apps": "['org.gnome.Calendar.desktop', 'org.gnome.Nautilus.desktop', 'firefox.desktop', 'org.gnome.Console.desktop', 'jetbrains-idea.desktop', 'thunderbird.desktop']"
  "/org/gnome/shell/welcome-dialog-last-shown-version": "'43.4'"
  "/org/gnome/shell/app-switcher/current-workspace-only": "true"
  "/org/gnome/shell/extensions/auto-move-windows/application-list": "['thunderbird.desktop:2', 'jetbrains-idea.desktop:3', 'signal-desktop.desktop:2', 'org.telegram.desktop.desktop:2', 'org.keepassxc.KeePassXC.desktop:4', 'org.gnome.Calendar.desktop:2']"
  "/org/gnome/shell/extensions/gtile/show-toggle-tiling-alt": "['<Control><Super>KP_Enter']"
  "/org/gnome/shell/extensions/gtile/theme": "'Default'"
  "/org/gnome/shell/keybindings/screenshot": "['<Super>Print']"
  "/org/gnome/shell/keybindings/screenshot-window": "['<Shift><Super>Print']"
  "/org/gnome/shell/weather/automatic-location": "true"
  "/org/gnome/shell/weather/locations": "[<(uint32 2, <('Göteborg', 'ESGP', true, [(1.0085094136262927, 0.2074032869608953)], [(1.007345872427158, 0.20885773963975227)])>)>]"

