---
- name: Install packages for keyboard-centric WMs
  become: true
  ansible.builtin.package:
    pkg: "{{ packages.headless }}"

- name: Install sway
  become: true
  ansible.builtin.package:
    pkg:
      - brightnessctl
      - gammastep # auto-colour temperature adjustment tool
      - grim # screenshot tool
      - jq # needed for keyboard-layout-changer
      - mako # notification daemon
      - pamixer
      - pavucontrol
      - sway
      - swayidle
      - swaylock
      - udiskie
      - waybar

- name: Install sway dependencies from AUR
  kewlfft.aur.aur:
    name:
      - swappy # screenshot-manipulating tool
      - azote # wallpaper manager
      - nwg-launchers # grid/bar launchers
      - autotiling # script for opening new windows more space-efficiently
      - wdisplays # tool for changing screen layouts dynamically
      - kanshi-git
    state: present
  become: true
  become_user: aur_builder

- name: Enable and start systemd user services
  ansible.builtin.systemd:
    name: "{{ item }}"
    scope: user
    state: started
    enabled: true
  loop:
    - kanshi.service
    - udiskie.service
    - nextcloud.service
    - gammastep-indicator.service
    - autotiling.service
    - mako.service

- name: Install terminal mail/office packages
  become: true
  ansible.builtin.package:
    pkg:
      - vdirsyncer
      - khard
      - neomutt
      - notmuch
      - isync
      - msmtp
      - pass
      - lynx

- name: "Configure vdirsyncer"
  ansible.builtin.import_tasks: vdirsyncer.yml
