---
- name: Install sway
  become: yes
  pacman:
    name:
      - sway
      - swaylock
      - swayidle
      - brightnessctl
      - gammastep # auto-colour temperature adjustment tool
      - grim # screenshot tool
      - waybar
      - jq # needed for keyboard-layout-changer
      - pavucontrol
    state: present

- name: Install sway dependencies from AUR
  aur:
    name:
      - swappy # screenshot-manipulating tool
      - azote # wallpaper manager
      - nwg-launchers # grid/bar launchers
      - autotiling # script for opening new windows more space-efficiently
      - wdisplays # tool for changing screen layouts dynamically
      - kanshi-git
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- import_tasks: nwg-launchers.yml
