---
- name: Init /etc/locale.gen
  become: yes
  ansible.builtin.template:
    dest: /etc/locale.gen
    src: locale.gen.j2

- name: run locale-gen
  become: yes
  ansible.builtin.command: locale-gen

- name: Init /etc/locale.conf
  become: yes
  ansible.builtin.template:
    dest: /etc/locale.conf
    src: locale.conf.j2

- name: Init /etc/vconsole.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    src: vconsole.conf
