---
- name: "Set time zone to {{ timezone }}"
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Sync time with hardware clock
  shell: hwclock --systohc