---
- name: "Set time zone to {{ timezone }}"
  become: yes
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    dest: /etc/localtime
    state: link

- name: Sync time with hardware clock
  become: yes
  ansible.builtin.command: hwclock --systohc
