---
- name: Enumerate created partitions
  shell: lsblk -n -o PATH "{{ install_disk }}" | tail -n +2
  register: _partitions
  changed_when: no

- name: Assign partitions to variables
  set_fact:
    efi_system_partition: "{{ _partitions.stdout_lines[0] }}"
    encrypted_lvm_partition: "{{ _partitions.stdout_lines[1] }}"
