---
- name: Update the system clock
  command: timedatectl set-ntp true

- import_tasks: erase_disk.yml
- import_tasks: create_partitions.yml
- import_tasks: collect_facts.yml
- import_tasks: setup_lvm_on_luks.yml
- import_tasks: format_partitions.yml
- import_tasks: mount_file_systems.yml
