---
- name: Ensure user aur_builder exists
  ansible.builtin.import_tasks: create_aur_builder_user.yml

- name: Install yay
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: present
  become: true
  become_user: aur_builder
