---
- name: Install intel microcode
  become: yes
  community.general.pacman:
    name: intel-ucode
    state: present
  when: "'GenuineIntel' in ansible_processor"
  notify:
    - regenerate initramfs
