---
- name: Install chezmoi
  become: yes
  pacman:
    package: chezmoi

- name: Init chezmoi
  command: chezmoi init https://github.com/macGYves/dotfiles.git

- name: chezmoi apply
  command: chezmoi apply
