---
- name: Install chezmoi
  become: yes
  community.general.pacman:
    package: chezmoi

- name: Check if ~/.local/share/chezmoi exists
  ansible.builtin.stat:
    path: ~/.local/share/chezmoi
  register: chezmoi_dir

- name: Init chezmoi
  ansible.builtin.command:  chezmoi init --apply https://github.com/macGYves/dotfiles.git --promptString email={{ user_email }}
  when: not chezmoi_dir.stat.exists

