---
- name: Install chezmoi
  become: true
  ansible.builtin.package:
    package: chezmoi

- name: Init chezmoi ( INTERACTION POTENTIALLY NEEDED! -> CHECK & PRESS YUBIKEY <- )
  ansible.builtin.command: chezmoi init --apply git@github.com:macGYves/maarch.git --promptString email="{{ user_email }}" --force
  args:
    creates: ~/.local/share/chezmoi
