---
- name: Install Uncomplicated Firewall
  become: true
  ansible.builtin.package:
    pkg: ufw
    state: present

- name: Start and enable ufw systemd service
  become: true
  ansible.builtin.systemd:
    name: ufw.service
    state: started
    enabled: true

- name: Start ufw
  become: true
  community.general.ufw:
    state: enabled
