---
- name: "Set timezone"
  ansible.builtin.import_tasks: timezone.yml

- name: Init /etc/systemd/timesyncd.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/timesyncd.conf
    src: timesyncd.conf
    mode: "0644"

- name: Enable systemd-timesyncd
  become: true
  ansible.builtin.systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true
