---
- name: "Install firefox"
  become: true
  ansible.builtin.package:
    pkg: firefox

- name: "Configure firefox profiles and preferences"
  ansible.builtin.include_role:
    name: basvandenbrink.firefox
