---
- name: Install iNet wireless daemon (iwd)
  become: yes
  pacman:
    name: iwd
    state: present

- name: Start and enable iwd systemd service
  become: yes
  ansible.builtin.systemd:
    name: iwd.service
    enabled: yes
