---
- name: "Import hostname.yml"
  ansible.builtin.import_tasks: hostname.yml

- name: Init /etc/hosts
  become: true
  ansible.builtin.template:
    dest: /etc/hosts
    src: "hosts.j2"
    mode: "0644"

- name: Install NetworkManager
  become: true
  ansible.builtin.package:
    name: networkmanager

- name: "Enable & start NetworkManager systemd service"
  become: true
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: true
