---
- import_tasks: hostname.yml

- name: Init /etc/hosts
  become: yes
  ansible.builtin.template:
    dest: /etc/hosts
    src: "hosts.j2"

- name: Install NetworkManager
  become: yes
  community.general.pacman:
    name: networkmanager

- name: "Enable & start NetworkManager systemd service"
  become: yes
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: yes
