---

- name: Install NetworkManager
  pacman:
    name:
      - networkmanager
      - network-manager-applet
    state: present


- name: Enable NetworkManager
  command: "systemctl enable NetworkManager.service"
