---
- name: Enable systemd-networkd
  become: yes
  command: "systemctl enable systemd-networkd.service"

- name: Copy systemd-networkd config files
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/network/
    src: "{{ item }}"
  with_fileglob:
    - "*.network"

- name: Enable systemd-resolved
  become: yes
  command: "systemctl enable systemd-resolved.service"

- name: Ensure systemd-resolved config folder exists
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory

- name: Copy systemd-resolved config file
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/resolved.conf.d/dns_servers.conf
    src: resolved/dns_servers.conf
