---
- name: Install syslinux
  become: yes
  package:
    name: syslinux gptfdisk

- name: Ensure syslinux dir exists
  become: yes
  file:
    path: /boot/syslinux
    state: directory

- name: Copy c32 into place
  become: yes
  copy:
    src: "{{ item }}"
    dest: /boot/syslinux
    mode: 640
    force: no
  with_fileglob:
    - /usr/lib/syslinux/bios/*.c32

- name: Install bootloader
  become: yes
  command: extlinux --install /boot/syslinux

- name: Install MBR
  become: yes
  shell: "dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/bios/gptmbr.bin of=/dev/sda"

- name: Copy syslinux.cfg
  become: yes
  template:
    src: syslinux.cfg.j2
    dest: /boot/syslinux/syslinux.cfg
    mode: 0640
