---
- name: Install bluetooth protocol stack
  become: yes
  community.general.pacman:
    pkg:
      - bluez
      - bluez-utils

- name: Start/Enable bluetooth systemd service
  become: yes
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: yes

- name: Init /etc/bluetooth/main.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/bluetooth/main.conf
    src: main.conf
