---
- name: Configure bluetooth
  become: true
  block:
    - name: Install bluetooth protocol stack
      ansible.builtin.package:
        pkg:
          - bluez
          - bluez-utils

    - name: Start/Enable bluetooth systemd service
      ansible.builtin.systemd:
        name: bluetooth.service
        state: started
        enabled: true

    - name: Init /etc/bluetooth/main.conf
      ansible.builtin.copy:
        dest: /etc/bluetooth/main.conf
        src: main.conf
        mode: "0644"
