---
- name: Check if efivars folder exists
  stat:
    path: /sys/firmware/efi/efivars
  register: efivars_info

- name: Set boot mode to BIOS
  set_fact:
    boot_mode: "bios"
  when: not efivars_info.stat.exists

- name: Set boot mode to UEFI
  set_fact:
    boot_mode: "uefi"
  when: efivars_info.stat.exists
