---
- name: Gathering hardware facts
  become: yes
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - hardware

- name: Save LUKS device UUID in fact
  become: yes
  set_fact:
    luks_device_uuid: "{{ ansible_device_links.uuids[item.key] | first}}"
  loop: "{{ ansible_device_links.labels | dict2items}}"
  when: partitions.luks.label in item.value
  changed_when: false
