---
- name: Gathering hardware facts
  become: yes
  setup:
    gather_subset:
      - "!all"
      - "!min"
      - hardware

- name: Save LUKS device UUID in fact
  become: yes
  set_fact:
    luks_device_uuid: "{{ ansible_device_links.uuids[item.key] | first}}"
  with_dict: "{{ ansible_device_links.labels }}"
  when: partitions.luks.label in item.value
  changed_when: false
