---
- name: Install udiskie
  community.general.pacman: 
    name: udiskie

- name: Ensure systemd user directory (~/.config/systemd/user) exists
  ansible.builtin.file:
    path: "~/.config/systemd/user"
    state: directory

- name: Ensure udiskie.service systemd unit is installed
  ansible.builtin.copy:
    dest: "~/.config/systemd/user"
    src: udiskie.service

- name: start and enable udiskie systemd service 
  ansible.builtin.systemd:
    name: udiskie.service
    scope: user
    state: started
    enabled: yes