---
- name: Create locale.gen
  copy:
    dest: /etc/locale.gen
    content: |
      en_GB.UTF-8 UTF-8
      de_DE.UTF-8 UTF-8
      sv_SE.UTF-8 UTF-8
    mode: 0644

- name: Run locale-gen
  shell: locale-gen

- name: Set LANG variable
  copy:
    dest: /etc/locale.conf
    content: LANG=de_DE.UTF-8
    mode: 0644

- name: Make swedish keyboard layout persistent
  copy:
    dest: /etc/vconsole.conf
    content: "KEYMAP=sv-latin1"
    mode: 0644