---
profile: production

exclude_paths:
  - dotfiles/
  - scripts/
  - .idea/
  - .github

offline: false

# Ansible-lint does not fail on warnings from the rules or tags listed below
warn_list:
  - command-instead-of-module
  - command-instead-of-shell
