---
- name: Customise a basic arch linux installation
  hosts: inventory.yml
  vars_prompt:
    - name: user_email
      prompt: "Your email address"
      private: no
    - name: yubikey_pin
      prompt: "YubiKey authenticator PIN"
      private: yes
  roles:
    - { role: packages, tags: "packages" }
    - yay
    - { role: yubikey, tags: "yubikey" }
    - { role: ssh, tags: "ssh" }
    - { role: dotfiles, tags: "dotfiles" }
    - { role: fonts, tags: "fonts" }
    - { role: shell, tags: "shell" }
    - { role: flatpak, tags: "flatpak" }
    - { role: gnome, tags: "gnome" }
    - { role: xdg-user-dirs, tags: "xdg-user-dirs" }
    - { role: dev-tools, tags: "dev-tools" }
    - { role: themes, tags: "themes" }
    - { role: office, tags: "office" }
    - { role: digikam, tags: "digikam" }
    - { role: virtualbox, tags: "virtualbox" }
    - { role: cleanup, tags: "cleanup" }
  handlers:
    - name: "regenerate initramfs"
      become: yes
      ansible.builtin.command: mkinitcpio -P
