---

- name: Customise a basic arch linux installation
  hosts: localhost
  user: root
  vars_prompt:
    - name: macgyves_password
      prompt: 'macgyves password'
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  roles:
    - network
    - base
    - { role: plasma, tags: 'plasma' }
    - { role: shell, tags: 'shell' }
    - { role: dev-tools, tags: 'dev-tools' }
    - { role: firewall, tags: 'firewall' }
  tasks:
    - name: Install more packages
      pacman:
        name: "{{ more_packages }}"
        state: present
      tags: 'install-packages'

# Grafikkartentreiber
#idea
# git-extras

# kde hotkeys
# bluetooth
# kde tastaturen

# yubikey
# ssh-key

# localectl set-x11-keymap sv-latin1
# git config
# git signing config



# security
# https://wiki.archlinux.org/index.php/Docker
# https://wiki.archlinux.org/index.php/TLP