---
- name: Customise a basic arch linux installation
  hosts: localhost
  vars_prompt:
    - name: user_password
      prompt: "user password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  roles:
    - { role: time, tags: "time" }
    - { role: network, tags: "network" }
    - { role: users, tags: "users" }
    - { role: l10n, tags: "l10n" }
    - { role: reflector, tags: "reflector" }
    - { role: ssd, tags: "ssd" }
    - { role: power_mgmt, tags: "power_mgmt" }
    - { role: firewall, tags: "firewall" }
    - { role: bluetooth, tags: "bluetooth" }
    - { role: yubikey, tags: "yubikey" }
    - { role: systemd-boot, tags: "systemd-boot" }
    - { role: kernel, tags: "kernel" }
  handlers:
    - name: "regenerate initramfs"
      become: yes
      ansible.builtin.command: mkinitcpio -P
