---
- name: Customise a basic arch linux installation
  hosts: localhost
  vars_prompt:
    - name: macgyves_password
      prompt: "macgyves password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  roles:
    - { role: network, tags: "network" }
    - base
    - { role: shell, tags: "shell" }
    - { role: dotfiles, tags: "dotfiles" }
    - { role: dev-tools, tags: "dev-tools" }
    - { role: firewall, tags: "firewall" }
    - { role: ssd, tags: "ssd" }
    - { role: alacritty, tags: "alacritty" }
    - { role: sway, tags: "sway" }
    - { role: bluetooth, tags: "bluetooth" }
    - { role: themes, tags: "themes" }
    - { role: yubikey, tags: "yubikey" }
    - { role: office, tags: "office" }
  tasks:
    - name: Install more packages
      pacman:
        name: "{{ packages.more }}"
        state: present
      tags: "install-packages"
