---
- name: Customise a basic arch linux installation
  hosts: localhost
  vars_prompt:
    - name: luks_password
      prompt: "luks password"
      private: yes
    - name: user_email
      prompt: "Your email address"
      private: no
    - name: yubikey_pin
      prompt: "YubiKey authenticator PIN"
      private: yes
  roles:
    - time
    - packages
    - users
    - yay
    - { role: ssd, tags: "ssd" }
    - { role: power_management, tags: "power_mgmt" }
    - { role: firewall, tags: "firewall" }
    - { role: bluetooth, tags: "bluetooth" }
    - { role: fonts, tags: "fonts" }
    - { role: shell, tags: "shell" }
    - { role: dotfiles, tags: "dotfiles" }
      #- { role: sway, tags: "sway" }
    - { role: gnome, tags: "gnome" }
    - { role: xdg-user-dirs, tags: "xdg-user-dirs" }
    - { role: flatpak, tags: "flatpak" }
    - { role: dev-tools, tags: "dev-tools" }
    - { role: themes, tags: "themes" }
    - { role: yubikey, tags: "yubikey" }
    - { role: ssh, tags: "ssh" }
    - { role: office, tags: "office" }
    - { role: digikam, tags: "digikam" }
    - { role: virtualbox, tags: "virtualbox" }
  handlers:
    - name: "regenerate initramfs"
      become: yes
      ansible.builtin.command: mkinitcpio -P
