---
- name: Spielplatz
  hosts: localhost
  tasks:
    - name: Check if there's a SSD
      command: lsblk --discard -J
      register: lsblk_info

    - debug:
        msg: "{{lsblk_info.stdout | from_json | json_query('blockdevices.disc-gran') }}"
