---

- name: Spielplatz
  hosts: localhost
  tasks:
    - name: Create LUKS container
      community.crypto.luks_device:
        device: "/dev/sda2"
        state: "present"
        passphrase: "lol"
        type: luks2

    - name: close the LUKS container
      community.crypto.luks_device:
        device: "/dev/sda2"
        state: "closed"
        name: "cryptlvm"
        passphrase: "g"

