---
- hosts: localhost
  user: root
  vars_prompt:
    - name: luks_password
      prompt: "luks password"
      private: yes
      confirm: yes
    - name: install_disk
      prompt: 'Installation target device (e.g. /dev/sda)'
      private: no
  roles:
    - os-install

- hosts: localhost_chroot
  user: root
  connection: chroot
  gather_facts: false
  vars:
    ansible_chroot_exe: arch-chroot
  vars_prompt:
    - name: root_password
      prompt: 'root password'
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  roles:
    - os-install--config
    - bootloader