---
- name: Bootstrap Arch Linux system
  hosts: localhost
  become: yes
  vars_files:
    - play_vars/install-os_vars.yml
  vars_prompt:
    - name: luks_password
      prompt: "luks password"
      private: yes
      confirm: yes
    - name: install_disk
      prompt: "Installation target device (e.g. /dev/sda)"
      private: no
    - name: root_password
      prompt: "root password"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
  pre_tasks:
    - set_fact:
        root_password: "{{ root_password }}"
    - name: Update the system clock
      command: timedatectl set-ntp true
  roles:
    - facts
    - os-install

- name: Continue Arch Linux installation in chroot
  hosts: localhost_chroot
  roles:
    - { role: localisation, tags: "localisation" }
    - { role: network, tags: "network" }
    - { role: microcode, tags: "microcode" }
    - { role: systemd-boot, tags: "bootloader" }
    - { role: kernel, tags: "kernel" }
  tasks:
    - name: Set root password
      user:
        name: root
        password: "{{ hostvars.localhost.root_password }}"

- name: Finish base OS installation
  hosts: localhost
  become: yes
  vars_files:
    - play_vars/install-os_vars.yml
  tasks:
    - name: Unmount partitions
      command: "umount -Rf {{ arch_root }}"

    - name: Reboot
      command: reboot now
