---
# https://wiki.archlinux.org/title/Reflector

- name: Install reflector
  become: true
  ansible.builtin.package:
    pkg:
      - reflector

- name: Init reflector.conf
  become: true
  ansible.builtin.copy:
    src: reflector.conf
    dest: /etc/xdg/reflector/reflector.conf
    mode: "0440"

- name: Enable reflector systemd service
  become: true
  ansible.builtin.systemd:
    name: reflector.service
    enabled: true

- name: Run reflector service weekly
  become: true
  ansible.builtin.systemd:
    name: reflector.timer
    enabled: true
    state: started
