---
- name: Install power management tools
  block:
    - name: Install TLP
      community.general.pacman:
        pkg: tlp

    - name: Init /etc/tlp.conf
      ansible.builtin.copy:
        dest: /etc/tlp.conf
        src: tlp.conf

    - name: Enable tlp.service
      ansible.builtin.systemd:
        name: tlp.service
        state: started
        enabled: yes
  become: yes
