---

- name: Install power management tools
  become: yes
  community.general.pacman:
    name: tlp

- name: Init /etc/tlp.conf
  become: yes
  ansible.builtin.copy:
    dest: /etc/tlp.conf
    src: tlp.conf

- name: Enable tlp.service 
  become: yes
  ansible.builtin.systemd:
    name: tlp.service
    state: started
    enabled: yes