---
- name: Install virtualbox
  become: yes
  community.general.pacman:
    pkg:
      - virtualbox
      - virtualbox-host-modules-arch
      - virtualbox-guest-iso

- name: "Add user {{ username }} to 'vboxusers' group"
  become: yes
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - vboxusers
    append: yes

- include_tasks: fix_ibt_bug.yml

- include_tasks: configure_as_vbox_guest.yml
  when: features.vbox_guest
