--- 
- name: Add aws-cli plugin to asdf
  ansible.builtin.command: "{{ asdf.bin }} plugin add awscli"
  register: asdf_awscli_plugin_installed
  failed_when: asdf_awscli_plugin_installed.rc > 2
  when: "'awscli' not in installed_asdf_plugins.stdout_lines"

- name: Install aws-cli
  ansible.builtin.command: "{{ asdf.bin }} install awscli latest"
  register: awscli_install_result
  changed_when: awscli_install_result.rc != 0

- name: "Make latest aws-cli version global default"
  ansible.builtin.command: "{{ asdf.bin }} global awscli latest"

- name: "Symlink ~/.asdf/shims/aws_completer to ~/.local/bin"
  # Reason: .zshrc relies upon ~/local/bin/aws_completer to exist for 
  # aws-cli auto-completion
  ansible.builtin.file:
    src: "~/.asdf/shims/aws_completer"
    dest: "~/.local/bin/aws_completer"
    state: link