---
- name: Install docker
  become: yes
  community.general.pacman:
    pkg:
      - docker
      - docker-compose

- name: "Add user {{ username }} to 'docker' group"
  become: yes
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
    append: yes

- name: Start/Enable docker systemd service
  become: yes
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes
