--- 
- name: Add java plugin to asdf
  ansible.builtin.command: "{{ asdf.bin }} plugin add java"
  register: asdf_java_plugin_installed
  failed_when: asdf_java_plugin_installed.rc > 2
  when: "'java' not in installed_asdf_plugins.stdout_lines"

- name: Install JDKS
  ansible.builtin.command: "{{ asdf.bin }} install java {{ item }}"
  loop: "{{ jdk.versions }}"
  register: jdk_install_result
  changed_when: jdk_install_result.rc != 0

- name: "Make {{ jdk.versions[0] }} global default JDK"
  ansible.builtin.command: "{{ asdf.bin }} global java {{ jdk.versions[0] }}"