---
- name: Clone asdf repository to {{ asdf.install_dir }}
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf.install_dir }}"
    version: "{{ asdf.version }}"

- include_tasks: java.yml
- include_tasks: maven.yml
- include_tasks: node.yml
