---
- name: Clone asdf repository to {{ asdf.install_dir }}
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ asdf.install_dir }}"
    version: "{{ asdf.version }}"

- name: List installed asdf plugins
  command: "{{ asdf.bin }} plugin list"
  register: installed_asdf_plugins
  failed_when: false
  changed_when: false

- include_tasks: java.yml
- include_tasks: maven.yml
- include_tasks: node.yml
- include_tasks: aws-cli.yml
