---
- name: "Ensure ~/.asdf does not exist"
  ansible.builtin.file:
    path: "~/.asdf"
    state: absent

- name: Clone asdf repository
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "~/.asdf"
    version: v0.8.0

- name: Add java plugin to asdf
  command: "~/.asdf/bin/asdf plugin add java"

- name: Install openjdk
  command: "~/.asdf/bin/asdf install java latest:openjdk"

- name: Add maven plugin to asdf
  command: "~/.asdf/bin/asdf plugin add maven"

- name: Install latest maven
  command: "~/.asdf/bin/asdf install maven latest"

- name: Add nodejs plugin to asdf
  command: "~/.asdf/bin/asdf plugin add nodejs"
