---
- name: Install asdf dependencies
  become: true
  community.general.pacman:
    package:
      - git
      - curl
      - python-pre-commit

- name: "Install dev tools via asdf"
  include_role:
    name: markosamuli.asdf
  vars:
    asdf_init_shell: false
    asdf_version: "{{ asdf.version }}"
    asdf_user: "{{ ansible_user_id }}"
    asdf_plugins:
      - name: "java"
        versions: "{{ jdk.versions }}"
        global: "{{ jdk.versions[0] }}"
      - name: "maven"
        versions: "{{ maven.versions }}"
        global: "{{ maven.versions[0] }}"
      - name: "nodejs"
        versions: "{{ nodejs.versions }}"
        global: "{{ nodejs.versions[0] }}"
      - name: "awscli"
        versions: ["2.11.16"]
        global: "2.11.16"

- name: "Install IDEs"
  kewlfft.aur.aur:
    name:
      - vscodium-bin
      - intellij-idea-ultimate-edition
  become: yes
  become_user: aur_builder

- include_tasks: docker.yml
