---
- name: Install asdf dependencies
  become: true
  community.general.pacman:
    package:
      - git
      - curl

- name: "Install dev tools via asdf"
  include_role: markosamuli.asdf
  vars:
    asdf_init_shell: false
    asdf_version: "{{ asdf.version }}"
    asdf_user: "{{ ansible_user_id }}"
    asdf_plugins:
      - name: "java"
        versions: "{{ jdk_versions }}"
        global: "{{ jdk_versions[0] }}"
      - name: "maven"
        versions: "{{ maven_versions }}"
        global: "{{ maven_versions[0] }}"
      - name: "nodejs"
        versions: "{{ nodejs_versions }}"
        global: "{{ nodejs_versions[0] }}"

- include_tasks: aws-cli.yml
