--- 

- name: Add nodejs plugin to asdf
  ansible.builtin.command: "{{ asdf.bin }} plugin add nodejs"
  register: asdf_nodejs_plugin_installed
  failed_when: asdf_nodejs_plugin_installed.rc > 2
  when: "'nodejs' not in installed_asdf_plugins.stdout_lines"

- name: Install nodejs versions
  ansible.builtin.command: "{{ asdf.bin }} install nodejs {{ item }}"
  loop: "{{ node.versions }}"
  register: node_install_result
  changed_when: node_install_result.rc != 0

- name: "Make {{ node.versions[0] }} global default node"
  ansible.builtin.command: "{{ asdf.bin }} global nodejs {{ node.versions[0] }}"

