---
- name: Install fonts
  become: yes
  community.general.pacman:
    pkg:
      - tex-gyre-fonts
      - ttf-dejavu
      - ttf-linux-libertine
      - ttf-hack
      - otf-font-awesome
      - inter-font
      - noto-fonts-emoji

- name: Install fonts from AUR
  aur:
    name: nerd-fonts-fira-code
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Ensure ~/.config/fontconfig directory exists
  ansible.builtin.file:
    path: ~/.config/fontconfig
    state: directory

- name: Copy fontconfig configuration
  ansible.builtin.copy:
    dest: ~/.config/fontconfig/fonts.conf
    src: font.conf
