---
- name: Install fonts
  become: yes
  pacman:
    name:
      - tex-gyre-fonts
      - ttf-dejavu
      - ttf-linux-libertine
      - ttf-hack
      - otf-font-awesome
      - inter-font

- name: Install fonts from AUR
  aur:
    name: nerd-fonts-fira-code
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder

- name: Copy fontconfig configuration
  ansible.builtin.copy:
    dest: ~/.config/fontconfig/fonts.conf
    src: local.conf
