---
- name: Install fonts
  become: true
  ansible.builtin.package:
    pkg:
      - tex-gyre-fonts
      - ttf-dejavu
      - ttf-linux-libertine
      - ttf-hack-nerd
      - inter-font
      - noto-fonts-emoji
      - ttf-roboto
      - ttf-roboto-mono-nerd

- name: Ensure ~/.config/fontconfig directory exists
  ansible.builtin.file:
    path: ~/.config/fontconfig
    state: directory
    mode: "0755"

- name: Copy fontconfig configuration
  ansible.builtin.copy:
    dest: ~/.config/fontconfig/fonts.conf
    src: font.conf
    mode: "0644"
