---
- name: Install YubiKey Personalization GUI
  become: yes
  pacman:
    name: 
      - yubikey-personalization-gui
      - yubikey-manager

- name: Install smartcard libs/tools
  become: yes
  pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid

- name: Start and enable pcscd.service
  become: yes
  systemd:
    name: pcscd.service
    state: started
    enabled: yes

- name: Install gcr  # pinentry-gnome3 depends on this
  become: yes
  pacman: 
    pkg: gcr
