---
- name: Install YubiKey - related packages
  become: true
  ansible.builtin.package:
    pkg:
      - yubikey-personalization-gui
      - yubikey-manager
      - libfido2 # dependency

- name: Install smartcard libs/tools
  become: true
  ansible.builtin.package:
    pkg:
      - pcsclite
      - libusb-compat
      - ccid
      - gcr # pinentry-gnome3 depends on this

- name: Start and enable pcscd.service
  become: true
  ansible.builtin.systemd:
    name: pcscd.service
    state: started
    enabled: true
