---
- name: Install YubiKey Personalization GUI
  become: yes
  community.general.pacman:
    name: 
      - yubikey-personalization-gui
      - yubikey-manager

- name: Install smartcard libs/tools
  become: yes
  community.general.pacman:
    name:
      - pcsclite
      - libusb-compat
      - ccid

- name: Start and enable pcscd.service
  become: yes
  ansible.builtin.systemd:
    name: pcscd.service
    state: started
    enabled: yes

- name: Install gcr  # pinentry-gnome3 depends on this
  become: yes
  community.general.pacman: 
    pkg: gcr

- import_tasks: ykfde.yml
