---
- name: Install YubiKey Personalization GUI
  become: yes
  community.general.pacman:
    pkg: 
      - yubikey-personalization-gui
      - yubikey-manager

- name: Install smartcard libs/tools
  become: yes
  community.general.pacman:
    pkg:
      - pcsclite
      - libusb-compat
      - ccid
      - gcr # pinentry-gnome3 depends on this

- name: Start and enable pcscd.service
  become: yes
  ansible.builtin.systemd:
    name: pcscd.service
    state: started
    enabled: yes

- import_tasks: ykfde.yml
