---
dev_tools_asdf:
  install_dir: "~/.asdf"
  version: "v0.11.3"

dev_tools_maven:
  versions:
    - "3.9.1"

dev_tools_jdk:
  versions:
    - "temurin-17.0.7+7"
    - "graalvm-22.3.0+java17"

dev_tools_nodejs:
  versions:
    - "18.16.0"
