---
- name: Setup swap file
  ansible.builtin.include_role:
    name: geerlingguy.swap
    apply:
      become: yes
  vars:
    swap_file_path: "{{ swapfile.path }}"
    swap_file_size_mb: "{{ swapfile.size }}"
    swap_swappiness: "5"
    swap_file_state: present
    swap_file_create_command: "btrfs filesystem mkswapfile --size {{ swapfile.size }} --uuid clear {{ swap_file_path }}"

- name: Register swap_file_offset
  become: yes
  ansible.builtin.command: btrfs inspect-internal map-swapfile -r "{{ swapfile.path }}"
  changed_when: false
  register: swap_file_offset

- name: Register swap_file_uuid
  become: yes
  ansible.builtin.command: findmnt -no UUID -T "{{ swapfile.path }}"
  changed_when: false
  register: swap_file_uuid

- name: Update bootloader entry
  #TODO: improve.
  become: yes
  ansible.builtin.lineinfile:
    path: /boot/loader/entries/arch.conf
    regexp: '^options (.*?)(resume=UUID={{ swap_file_uuid.stdout }}\s+resume_offset={{ swap_file_offset.stdout }})?$'
    line: 'options \1 resume=UUID={{ swap_file_uuid.stdout }} resume_offset={{ swap_file_offset.stdout }}'
    backrefs: yes

- name: Add resume hook to /etc/mkinitcpio.conf before fsck
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS=(.*)(?<!resume)\s+fsck(.*)$'
    line: 'HOOKS=\1 resume fsck\2'
    backrefs: yes
  notify:
    - "regenerate initramfs"

- name: Minimize hibernation image size
  become: yes
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/hibernation_image_size.conf
    src: hibernation_image_size.conf
