---
- name: "Include role: swap"
  ansible.builtin.include_role:
    name: swap

- name: Configure system to minimize hibernation image size
  become: true
  ansible.builtin.copy:
    dest: /etc/tmpfiles.d/hibernation_image_size.conf
    src: hibernation_image_size.conf
    mode: "0644"
